default-cache-ttl 34560000
max-cache-ttl 34560000
# Allows authenticating via the GPG key without creating a separate SSH key
enable-ssh-support

# Requires GPG4Win + Kleopatra
# gpg-agent in Windows can be found in C:\Users\bosco\AppData\Roaming\gnupg\gpg-agent.conf
# pinentry-program "/mnt/d/Program Files (x86)/Gpg4win/bin/pinentry.exe"
# Much slower and prone to errors
# pinentry-program "/mnt/d/Program Files (x86)/GnuPG/bin/pinentry-basic.exe"

# Uses native pinentry (separate screen inside Terminal)
pinentry-program /usr/bin/pinentry
allow-loopback-pinentry

# Uses inline pinentry (preferred, requires install)
# Or `sudo apt install pinentry-tty`
# pinentry-program /usr/bin/pinentry-tty
# or `brew install pinentry-tty`
# pinentry-program /home/linuxbrew/.linuxbrew/bin/pinentry-tty
