set-option -g default-terminal "screen-256color"

set-option -g status-bg black
set-option -g status-fg white
# set -g status-bg default
# set -g status-fg white

set -g status-interval 1
set -g status-right-length 100
set -g status-right '#(cat ~/.tmux-status)'

# Set pane border colors
set -g pane-border-style fg=white
set -g pane-active-border-style fg=white

# Set window status colors
setw -g window-status-style bg=default,fg=white
setw -g window-status-current-style bg=default,fg=white

# Set the display time to default colors
set -g message-style bg=default,fg=white
